# Series

In [54]:
import pandas as pd

a = [1,2,3,4]
var1 = pd.Series(a)

print(var1)

0    1
1    2
2    3
3    4
dtype: int64

In [55]:
b = [1,2,3,4]
var = pd.Series(b,dtype=float,index=['a','b','c','d'])
print(var)

a    1.0
b    2.0
c    3.0
d    4.0
dtype: float64

In [56]:
dic = {'Name':['Anand','Sanjay','Vaishu'],'RollNo':[65,56,57]}

var = pd.Series(dic)
print(var)

Name      [Anand, Sanjay, Vaishu]
RollNo               [65, 56, 57]
dtype: object

In [57]:
s = pd.Series(12,index=[1,2,3,4,5,6,7])
print(s)

1    12
2    12
3    12
4    12
5    12
6    12
7    12
dtype: int64

In [58]:
s1 = pd.Series(12,index=[1,2,3,4,5,6,7])
s2 = pd.Series(12,index=[1,2,3,4])
print(s1+s2)

1    24.0
2    24.0
3    24.0
4    24.0
5     NaN
6     NaN
7     NaN
dtype: float64

# DataFrame

In [59]:
l = [1,2,3,4,5,6]
var = pd.DataFrame(l)

print(var)
print(type(var))

   0
0  1
1  2
2  3
3  4
4  5
5  6
<class 'pandas.core.frame.DataFrame'>

In [60]:
a = {'a':[1,2,3,4,5],'b':[1,2,3,4,5]}

var = pd.DataFrame(a)

print(var)
print(type(var))

   a  b
0  1  1
1  2  2
2  3  3
3  4  4
4  5  5
<class 'pandas.core.frame.DataFrame'>

In [61]:
a = {'a':[1,2,3,4,5],'b':[1,2,3,4,5],65:[1,2,3,4,5]}

var = pd.DataFrame(a)

print(type(var))
print(var)

print(var['a'][2])

<class 'pandas.core.frame.DataFrame'>
   a  b  65
0  1  1   1
1  2  2   2
2  3  3   3
3  4  4   4
4  5  5   5
3

In [62]:
a = {'a':[1,2,3,4,5],'b':[1,2,3,4,5],65:[1,2,3,4,5]}

var = pd.DataFrame(a,columns=['b',65],index=['a','b','c','d','e'])

print(type(var))
print(var)

print(var['b'][0])

<class 'pandas.core.frame.DataFrame'>
   b  65
a  1   1
b  2   2
c  3   3
d  4   4
e  5   5
1

In [63]:
list = [[1,2,3,4,5],[6,7,8,9,10]]

var = pd.DataFrame(list)

print(var)

print(var[1][0])

   0  1  2  3   4
0  1  2  3  4   5
1  6  7  8  9  10
2

In [64]:
dic = {'a':pd.Series([1,2,3,4,5]),'b':pd.Series([6,7,8,9,10])}

var = pd.DataFrame(dic)

print(var)


print(var['a'][4])
print(var['b'][4])

   a   b
0  1   6
1  2   7
2  3   8
3  4   9
4  5  10
5
10

# Arthematic Operations

In [65]:
a = pd.DataFrame({"A":[1,2,3,4],"B":[5,6,7,8]})
a

   A  B
0  1  5
1  2  6
2  3  7
3  4  8

In [66]:
a["C"]=a["A"]+a["B"]
print(a)

   A  B   C
0  1  5   6
1  2  6   8
2  3  7  10
3  4  8  12

In [67]:
a["C"]=a["A"]-a["B"]
print(a)

   A  B  C
0  1  5 -4
1  2  6 -4
2  3  7 -4
3  4  8 -4

In [68]:
a["C"]=a["A"]*a["B"]
print(a)

   A  B   C
0  1  5   5
1  2  6  12
2  3  7  21
3  4  8  32

In [69]:
a["C"]=a["A"]/a["B"]
print(a)

   A  B         C
0  1  5  0.200000
1  2  6  0.333333
2  3  7  0.428571
3  4  8  0.500000

In [70]:
a["C"]=a["A"]%a["B"]
print(a)

   A  B  C
0  1  5  1
1  2  6  2
2  3  7  3
3  4  8  4

In [71]:
a["Java"]=a["A"]>2
a["Python"]=a["B"]>5
print(a)

   A  B  C   Java  Python
0  1  5  1  False   False
1  2  6  2  False    True
2  3  7  3   True    True
3  4  8  4   True    True

# Insert

In [72]:
b = pd.DataFrame({"A":[1,2,3,4,5],"B":[9,8,7,6,5]})
b

   A  B
0  1  9
1  2  8
2  3  7
3  4  6
4  5  5

In [73]:
# b.insert()  there will be 3 parameters... 1st is index number 2nd is name of column and 3rd is the data which is to be printed
b.insert(1,"C",[6,3,7,6,5])
b.insert(0,"Anand",b["A"])
print(b)

   Anand  A  C  B
0      1  1  6  9
1      2  2  3  8
2      3  3  7  7
3      4  4  6  6
4      5  5  5  5

In [74]:
b["D"] = b["A"][:3]
b

   Anand  A  C  B    D
0      1  1  6  9  1.0
1      2  2  3  8  2.0
2      3  3  7  7  3.0
3      4  4  6  6  NaN
4      5  5  5  5  NaN

# Delete

In [75]:
deleted_column = b.pop('B')
print(b)
deleted_column
print(deleted_column)

   Anand  A  C    D
0      1  1  6  1.0
1      2  2  3  2.0
2      3  3  7  3.0
3      4  4  6  NaN
4      5  5  5  NaN
0    9
1    8
2    7
3    6
4    5
Name: B, dtype: int64

# Write CSV

In [77]:
dic = {"A":[1,2,3,4,5,6],"B":[6,5,4,3,2,1],"C":[3,1,4,2,6,5]}

d = pd.DataFrame(dic)

print(d)

d.to_csv("Basic_csv_file.csv",index=False)

   A  B  C
0  1  6  3
1  2  5  1
2  3  4  4
3  4  3  2
4  5  2  6
5  6  1  5

# Read CSV

In [97]:
new_csv_ML = pd.read_csv("C:\\Users\\anand\\OneDrive\\Desktop\\ml-learning\\machine_learning_data.csv")
print(new_csv_ML)

           Algorithm          Type        Use_Case Complexity
0  Linear Regression    Supervised      Prediction        Low
1      Decision Tree    Supervised  Classification     Medium
2                SVM    Supervised  Classification       High
3                KNN    Supervised  Classification     Medium
4      Random Forest    Supervised  Classification       High
5        Naive Bayes    Supervised  Classification        Low
6            K-Means  Unsupervised      Clustering     Medium
7     Neural Network    Supervised   Deep Learning  Very High

In [98]:
new_csv_ML = pd.read_csv("C:\\Users\\anand\\OneDrive\\Desktop\\ml-learning\\machine_learning_data.csv",nrows=3)
print(new_csv_ML)

           Algorithm        Type        Use_Case Complexity
0  Linear Regression  Supervised      Prediction        Low
1      Decision Tree  Supervised  Classification     Medium
2                SVM  Supervised  Classification       High

In [99]:
new_csv_ML = pd.read_csv("C:\\Users\\anand\\OneDrive\\Desktop\\ml-learning\\machine_learning_data.csv",usecols = ["Algorithm","Complexity"])
new_csv_ML

           Algorithm Complexity
0  Linear Regression        Low
1      Decision Tree     Medium
2                SVM       High
3                KNN     Medium
4      Random Forest       High
5        Naive Bayes        Low
6            K-Means     Medium
7     Neural Network  Very High

In [100]:
new_csv_ML = pd.read_csv("C:\\Users\\anand\\OneDrive\\Desktop\\ml-learning\\machine_learning_data.csv",usecols = [2,3])
new_csv_ML

         Use_Case Complexity
0      Prediction        Low
1  Classification     Medium
2  Classification       High
3  Classification     Medium
4  Classification       High
5  Classification        Low
6      Clustering     Medium
7   Deep Learning  Very High

In [101]:
new_csv_ML = pd.read_csv("C:\\Users\\anand\\OneDrive\\Desktop\\ml-learning\\machine_learning_data.csv",skiprows=2)
new_csv_ML

    Decision Tree    Supervised  Classification     Medium
0             SVM    Supervised  Classification       High
1             KNN    Supervised  Classification     Medium
2   Random Forest    Supervised  Classification       High
3     Naive Bayes    Supervised  Classification        Low
4         K-Means  Unsupervised      Clustering     Medium
5  Neural Network    Supervised   Deep Learning  Very High

In [102]:
new_csv_ML = pd.read_csv("C:\\Users\\anand\\OneDrive\\Desktop\\ml-learning\\machine_learning_data.csv",skiprows=[0,3,4])
new_csv_ML

  Linear Regression    Supervised      Prediction        Low
0     Decision Tree    Supervised  Classification     Medium
1     Random Forest    Supervised  Classification       High
2       Naive Bayes    Supervised  Classification        Low
3           K-Means  Unsupervised      Clustering     Medium
4    Neural Network    Supervised   Deep Learning  Very High

In [108]:
new_csv_ML = pd.read_csv("C:\\Users\\anand\\OneDrive\\Desktop\\ml-learning\\machine_learning_data.csv")
new_csv_ML.columns = ["Algorithm","Type","Category","Complexcity"]
new_csv_ML

           Algorithm          Type        Category Complexcity
0  Linear Regression    Supervised      Prediction         Low
1      Decision Tree    Supervised  Classification      Medium
2                SVM    Supervised  Classification        High
3                KNN    Supervised  Classification      Medium
4      Random Forest    Supervised  Classification        High
5        Naive Bayes    Supervised  Classification         Low
6            K-Means  Unsupervised      Clustering      Medium
7     Neural Network    Supervised   Deep Learning   Very High

In [109]:
new_csv_ML = pd.read_csv("C:\\Users\\anand\\OneDrive\\Desktop\\ml-learning\\machine_learning_data.csv",index_col = "Algorithm")
new_csv_ML

                           Type        Use_Case Complexity
Algorithm
Linear Regression    Supervised      Prediction        Low
Decision Tree        Supervised  Classification     Medium
SVM                  Supervised  Classification       High
KNN                  Supervised  Classification     Medium
Random Forest        Supervised  Classification       High
Naive Bayes          Supervised  Classification        Low
K-Means            Unsupervised      Clustering     Medium
Neural Network       Supervised   Deep Learning  Very High

In [110]:
new_csv_ML = pd.read_csv("C:\\Users\\anand\\OneDrive\\Desktop\\ml-learning\\machine_learning_data.csv",header = 2)
new_csv_ML

    Decision Tree    Supervised  Classification     Medium
0             SVM    Supervised  Classification       High
1             KNN    Supervised  Classification     Medium
2   Random Forest    Supervised  Classification       High
3     Naive Bayes    Supervised  Classification        Low
4         K-Means  Unsupervised      Clustering     Medium
5  Neural Network    Supervised   Deep Learning  Very High

In [113]:
new_csv_ML = pd.read_csv("C:\\Users\\anand\\OneDrive\\Desktop\\ml-learning\\machine_learning_data.csv",names = ["anand","vaishu","sanjay","vinay"])
new_csv_ML

               anand        vaishu          sanjay       vinay
0          Algorithm          Type        Use_Case  Complexity
1  Linear Regression    Supervised      Prediction         Low
2      Decision Tree    Supervised  Classification      Medium
3                SVM    Supervised  Classification        High
4                KNN    Supervised  Classification      Medium
5      Random Forest    Supervised  Classification        High
6        Naive Bayes    Supervised  Classification         Low
7            K-Means  Unsupervised      Clustering      Medium
8     Neural Network    Supervised   Deep Learning   Very High

In [116]:
new_csv_ML = pd.read_csv("C:\\Users\\anand\\OneDrive\\Desktop\\ml-learning\\machine_learning_data.csv",header = None,prefix = "columns")
new_csv_ML

            columns0      columns1        columns2    columns3
0          Algorithm          Type        Use_Case  Complexity
1  Linear Regression    Supervised      Prediction         Low
2      Decision Tree    Supervised  Classification      Medium
3                SVM    Supervised  Classification        High
4                KNN    Supervised  Classification      Medium
5      Random Forest    Supervised  Classification        High
6        Naive Bayes    Supervised  Classification         Low
7            K-Means  Unsupervised      Clustering      Medium
8     Neural Network    Supervised   Deep Learning   Very High