# Series

In [1]:
import pandas as pd

a = [1,2,3,4]
var1 = pd.Series(a)

print(var1)

0    1
1    2
2    3
3    4
dtype: int64

In [2]:
b = [1,2,3,4]
var = pd.Series(b,dtype=float,index=['a','b','c','d'])
print(var)

a    1.0
b    2.0
c    3.0
d    4.0
dtype: float64

In [3]:
dic = {'Name':['Anand','Sanjay','Vaishu'],'RollNo':[65,56,57]}

var = pd.Series(dic)
print(var)

Name      [Anand, Sanjay, Vaishu]
RollNo               [65, 56, 57]
dtype: object

In [4]:
s = pd.Series(12,index=[1,2,3,4,5,6,7])
print(s)

1    12
2    12
3    12
4    12
5    12
6    12
7    12
dtype: int64

In [5]:
s1 = pd.Series(12,index=[1,2,3,4,5,6,7])
s2 = pd.Series(12,index=[1,2,3,4])
print(s1+s2)

1    24.0
2    24.0
3    24.0
4    24.0
5     NaN
6     NaN
7     NaN
dtype: float64

# DataFrame

In [6]:
l = [1,2,3,4,5,6]
var = pd.DataFrame(l)

print(var)
print(type(var))

   0
0  1
1  2
2  3
3  4
4  5
5  6
<class 'pandas.core.frame.DataFrame'>

In [7]:
a = {'a':[1,2,3,4,5],'b':[1,2,3,4,5]}

var = pd.DataFrame(a)

print(var)
print(type(var))

   a  b
0  1  1
1  2  2
2  3  3
3  4  4
4  5  5
<class 'pandas.core.frame.DataFrame'>

In [8]:
a = {'a':[1,2,3,4,5],'b':[1,2,3,4,5],65:[1,2,3,4,5]}

var = pd.DataFrame(a)

print(type(var))
print(var)

print(var['a'][2])

<class 'pandas.core.frame.DataFrame'>
   a  b  65
0  1  1   1
1  2  2   2
2  3  3   3
3  4  4   4
4  5  5   5
3

In [9]:
a = {'a':[1,2,3,4,5],'b':[1,2,3,4,5],65:[1,2,3,4,5]}

var = pd.DataFrame(a,columns=['b',65],index=['a','b','c','d','e'])

print(type(var))
print(var)

print(var['b'][0])

<class 'pandas.core.frame.DataFrame'>
   b  65
a  1   1
b  2   2
c  3   3
d  4   4
e  5   5
1

In [10]:
list = [[1,2,3,4,5],[6,7,8,9,10]]

var = pd.DataFrame(list)

print(var)

print(var[1][0])

   0  1  2  3   4
0  1  2  3  4   5
1  6  7  8  9  10
2

In [11]:
dic = {'a':pd.Series([1,2,3,4,5]),'b':pd.Series([6,7,8,9,10])}

var = pd.DataFrame(dic)

print(var)


print(var['a'][4])
print(var['b'][4])

   a   b
0  1   6
1  2   7
2  3   8
3  4   9
4  5  10
5
10

# Arthematic Operations

In [12]:
a = pd.DataFrame({"A":[1,2,3,4],"B":[5,6,7,8]})
a

   A  B
0  1  5
1  2  6
2  3  7
3  4  8

In [13]:
a["C"]=a["A"]+a["B"]
print(a)

   A  B   C
0  1  5   6
1  2  6   8
2  3  7  10
3  4  8  12

In [14]:
a["C"]=a["A"]-a["B"]
print(a)

   A  B  C
0  1  5 -4
1  2  6 -4
2  3  7 -4
3  4  8 -4

In [15]:
a["C"]=a["A"]*a["B"]
print(a)

   A  B   C
0  1  5   5
1  2  6  12
2  3  7  21
3  4  8  32

In [16]:
a["C"]=a["A"]/a["B"]
print(a)

   A  B         C
0  1  5  0.200000
1  2  6  0.333333
2  3  7  0.428571
3  4  8  0.500000

In [17]:
a["C"]=a["A"]%a["B"]
print(a)

   A  B  C
0  1  5  1
1  2  6  2
2  3  7  3
3  4  8  4

In [18]:
a["Java"]=a["A"]>2
a["Python"]=a["B"]>5
print(a)

   A  B  C   Java  Python
0  1  5  1  False   False
1  2  6  2  False    True
2  3  7  3   True    True
3  4  8  4   True    True

# Insert

In [19]:
b = pd.DataFrame({"A":[1,2,3,4,5],"B":[9,8,7,6,5]})
b

   A  B
0  1  9
1  2  8
2  3  7
3  4  6
4  5  5

In [20]:
# b.insert()  there will be 3 parameters... 1st is index number 2nd is name of column and 3rd is the data which is to be printed
b.insert(1,"C",[6,3,7,6,5])
b.insert(0,"Anand",b["A"])
print(b)

   Anand  A  C  B
0      1  1  6  9
1      2  2  3  8
2      3  3  7  7
3      4  4  6  6
4      5  5  5  5

In [21]:
b["D"] = b["A"][:3]
b

   Anand  A  C  B    D
0      1  1  6  9  1.0
1      2  2  3  8  2.0
2      3  3  7  7  3.0
3      4  4  6  6  NaN
4      5  5  5  5  NaN

# Delete

In [22]:
deleted_column = b.pop('B')
print(b)
deleted_column
print(deleted_column)

   Anand  A  C    D
0      1  1  6  1.0
1      2  2  3  2.0
2      3  3  7  3.0
3      4  4  6  NaN
4      5  5  5  NaN
0    9
1    8
2    7
3    6
4    5
Name: B, dtype: int64

# Write CSV

In [23]:
dic = {"A":[1,2,3,4,5,6],"B":[6,5,4,3,2,1],"C":[3,1,4,2,6,5]}

d = pd.DataFrame(dic)

print(d)

d.to_csv("Basic_csv_file.csv",index=False)

   A  B  C
0  1  6  3
1  2  5  1
2  3  4  4
3  4  3  2
4  5  2  6
5  6  1  5

# Read CSV

In [24]:
new_csv_ML = pd.read_csv("C:\\Users\\anand\\OneDrive\\Desktop\\ml-learning\\machine_learning_data.csv")
print(new_csv_ML)

           Algorithm          Type        Use_Case Complexity
0  Linear Regression    Supervised      Prediction        Low
1      Decision Tree    Supervised  Classification     Medium
2                SVM    Supervised  Classification       High
3                KNN    Supervised  Classification     Medium
4      Random Forest    Supervised  Classification       High
5        Naive Bayes    Supervised  Classification        Low
6            K-Means  Unsupervised      Clustering     Medium
7     Neural Network    Supervised   Deep Learning  Very High

In [25]:
new_csv_ML = pd.read_csv("C:\\Users\\anand\\OneDrive\\Desktop\\ml-learning\\machine_learning_data.csv",nrows=3)
print(new_csv_ML)

           Algorithm        Type        Use_Case Complexity
0  Linear Regression  Supervised      Prediction        Low
1      Decision Tree  Supervised  Classification     Medium
2                SVM  Supervised  Classification       High

In [26]:
new_csv_ML = pd.read_csv("C:\\Users\\anand\\OneDrive\\Desktop\\ml-learning\\machine_learning_data.csv",usecols = ["Algorithm","Complexity"])
new_csv_ML

           Algorithm Complexity
0  Linear Regression        Low
1      Decision Tree     Medium
2                SVM       High
3                KNN     Medium
4      Random Forest       High
5        Naive Bayes        Low
6            K-Means     Medium
7     Neural Network  Very High

In [27]:
new_csv_ML = pd.read_csv("C:\\Users\\anand\\OneDrive\\Desktop\\ml-learning\\machine_learning_data.csv",usecols = [2,3])
new_csv_ML

         Use_Case Complexity
0      Prediction        Low
1  Classification     Medium
2  Classification       High
3  Classification     Medium
4  Classification       High
5  Classification        Low
6      Clustering     Medium
7   Deep Learning  Very High

In [28]:
new_csv_ML = pd.read_csv("C:\\Users\\anand\\OneDrive\\Desktop\\ml-learning\\machine_learning_data.csv",skiprows=2)
new_csv_ML

    Decision Tree    Supervised  Classification     Medium
0             SVM    Supervised  Classification       High
1             KNN    Supervised  Classification     Medium
2   Random Forest    Supervised  Classification       High
3     Naive Bayes    Supervised  Classification        Low
4         K-Means  Unsupervised      Clustering     Medium
5  Neural Network    Supervised   Deep Learning  Very High

In [29]:
new_csv_ML = pd.read_csv("C:\\Users\\anand\\OneDrive\\Desktop\\ml-learning\\machine_learning_data.csv",skiprows=[0,3,4])
new_csv_ML

  Linear Regression    Supervised      Prediction        Low
0     Decision Tree    Supervised  Classification     Medium
1     Random Forest    Supervised  Classification       High
2       Naive Bayes    Supervised  Classification        Low
3           K-Means  Unsupervised      Clustering     Medium
4    Neural Network    Supervised   Deep Learning  Very High

In [30]:
new_csv_ML = pd.read_csv("C:\\Users\\anand\\OneDrive\\Desktop\\ml-learning\\machine_learning_data.csv")
new_csv_ML.columns = ["Algorithm","Type","Category","Complexcity"]
new_csv_ML

           Algorithm          Type        Category Complexcity
0  Linear Regression    Supervised      Prediction         Low
1      Decision Tree    Supervised  Classification      Medium
2                SVM    Supervised  Classification        High
3                KNN    Supervised  Classification      Medium
4      Random Forest    Supervised  Classification        High
5        Naive Bayes    Supervised  Classification         Low
6            K-Means  Unsupervised      Clustering      Medium
7     Neural Network    Supervised   Deep Learning   Very High

In [31]:
new_csv_ML = pd.read_csv("C:\\Users\\anand\\OneDrive\\Desktop\\ml-learning\\machine_learning_data.csv",index_col = "Algorithm")
new_csv_ML

                           Type        Use_Case Complexity
Algorithm
Linear Regression    Supervised      Prediction        Low
Decision Tree        Supervised  Classification     Medium
SVM                  Supervised  Classification       High
KNN                  Supervised  Classification     Medium
Random Forest        Supervised  Classification       High
Naive Bayes          Supervised  Classification        Low
K-Means            Unsupervised      Clustering     Medium
Neural Network       Supervised   Deep Learning  Very High

In [32]:
new_csv_ML = pd.read_csv("C:\\Users\\anand\\OneDrive\\Desktop\\ml-learning\\machine_learning_data.csv",header = 4)
new_csv_ML

              KNN    Supervised  Classification     Medium
0   Random Forest    Supervised  Classification       High
1     Naive Bayes    Supervised  Classification        Low
2         K-Means  Unsupervised      Clustering     Medium
3  Neural Network    Supervised   Deep Learning  Very High

In [33]:
new_csv_ML = pd.read_csv("C:\\Users\\anand\\OneDrive\\Desktop\\ml-learning\\machine_learning_data.csv",names = ["anand","vaishu","sanjay","vinay"])
new_csv_ML

               anand        vaishu          sanjay       vinay
0          Algorithm          Type        Use_Case  Complexity
1  Linear Regression    Supervised      Prediction         Low
2      Decision Tree    Supervised  Classification      Medium
3                SVM    Supervised  Classification        High
4                KNN    Supervised  Classification      Medium
5      Random Forest    Supervised  Classification        High
6        Naive Bayes    Supervised  Classification         Low
7            K-Means  Unsupervised      Clustering      Medium
8     Neural Network    Supervised   Deep Learning   Very High

In [34]:
new_csv_ML = pd.read_csv("C:\\Users\\anand\\OneDrive\\Desktop\\ml-learning\\machine_learning_data.csv",header = None,prefix = "columns")
new_csv_ML

            columns0      columns1        columns2    columns3
0          Algorithm          Type        Use_Case  Complexity
1  Linear Regression    Supervised      Prediction         Low
2      Decision Tree    Supervised  Classification      Medium
3                SVM    Supervised  Classification        High
4                KNN    Supervised  Classification      Medium
5      Random Forest    Supervised  Classification        High
6        Naive Bayes    Supervised  Classification         Low
7            K-Means  Unsupervised      Clustering      Medium
8     Neural Network    Supervised   Deep Learning   Very High

In [35]:
new_csv_ML = pd.read_csv("C:\\Users\\anand\\OneDrive\\Desktop\\ml-learning\\machine_learning_data.csv")
new_csv_ML

           Algorithm          Type        Use_Case Complexity
0  Linear Regression    Supervised      Prediction        Low
1      Decision Tree    Supervised  Classification     Medium
2                SVM    Supervised  Classification       High
3                KNN    Supervised  Classification     Medium
4      Random Forest    Supervised  Classification       High
5        Naive Bayes    Supervised  Classification        Low
6            K-Means  Unsupervised      Clustering     Medium
7     Neural Network    Supervised   Deep Learning  Very High

# Pandas Functions

In [36]:
new_csv_ML.index

RangeIndex(start=0, stop=8, step=1)

In [37]:
new_csv_ML.columns

Index(['Algorithm', 'Type', 'Use_Case', 'Complexity'], dtype='object')

In [38]:
new_csv_ML.describe()

                Algorithm        Type        Use_Case Complexity
count                   8           8               8          8
unique                  8           2               4          4
top     Linear Regression  Supervised  Classification     Medium
freq                    1           7               5          3

In [57]:
new_csv_ML.head(4)

           Algorithm          Type        Use_Case Complexity
0  Linear Regression    Supervised      Prediction        Low
1              Anand    Supervised  Classification     Medium
2                SVM    Supervised  Classification       High
3                KNN  Unsupervised  Classification     Medium

In [40]:
new_csv_ML.tail(2)

        Algorithm          Type       Use_Case Complexity
6         K-Means  Unsupervised     Clustering     Medium
7  Neural Network    Supervised  Deep Learning  Very High

In [41]:
new_csv_ML[2:5]

       Algorithm        Type        Use_Case Complexity
2            SVM  Supervised  Classification       High
3            KNN  Supervised  Classification     Medium
4  Random Forest  Supervised  Classification       High

In [42]:
new_csv_ML.index.array

<PandasArray>
[0, 1, 2, 3, 4, 5, 6, 7]
Length: 8, dtype: int64

In [43]:
new_csv_ML.to_numpy()

array([['Linear Regression', 'Supervised', 'Prediction', 'Low'],
       ['Decision Tree', 'Supervised', 'Classification', 'Medium'],
       ['SVM', 'Supervised', 'Classification', 'High'],
       ['KNN', 'Supervised', 'Classification', 'Medium'],
       ['Random Forest', 'Supervised', 'Classification', 'High'],
       ['Naive Bayes', 'Supervised', 'Classification', 'Low'],
       ['K-Means', 'Unsupervised', 'Clustering', 'Medium'],
       ['Neural Network', 'Supervised', 'Deep Learning', 'Very High']],
      dtype=object)

In [44]:
print(type(new_csv_ML))

<class 'pandas.core.frame.DataFrame'>

In [45]:
import numpy as np
a = np.asarray(new_csv_ML)
a

array([['Linear Regression', 'Supervised', 'Prediction', 'Low'],
       ['Decision Tree', 'Supervised', 'Classification', 'Medium'],
       ['SVM', 'Supervised', 'Classification', 'High'],
       ['KNN', 'Supervised', 'Classification', 'Medium'],
       ['Random Forest', 'Supervised', 'Classification', 'High'],
       ['Naive Bayes', 'Supervised', 'Classification', 'Low'],
       ['K-Means', 'Unsupervised', 'Clustering', 'Medium'],
       ['Neural Network', 'Supervised', 'Deep Learning', 'Very High']],
      dtype=object)

In [46]:
new_csv_ML.sort_index(axis=0,ascending=False)

           Algorithm          Type        Use_Case Complexity
7     Neural Network    Supervised   Deep Learning  Very High
6            K-Means  Unsupervised      Clustering     Medium
5        Naive Bayes    Supervised  Classification        Low
4      Random Forest    Supervised  Classification       High
3                KNN    Supervised  Classification     Medium
2                SVM    Supervised  Classification       High
1      Decision Tree    Supervised  Classification     Medium
0  Linear Regression    Supervised      Prediction        Low

In [47]:
new_csv_ML["Algorithm"][1] = "Anand"
new_csv_ML

           Algorithm          Type        Use_Case Complexity
0  Linear Regression    Supervised      Prediction        Low
1              Anand    Supervised  Classification     Medium
2                SVM    Supervised  Classification       High
3                KNN    Supervised  Classification     Medium
4      Random Forest    Supervised  Classification       High
5        Naive Bayes    Supervised  Classification        Low
6            K-Means  Unsupervised      Clustering     Medium
7     Neural Network    Supervised   Deep Learning  Very High

In [48]:
new_csv_ML.loc[3,"Type"] = "Unsupervised"
new_csv_ML

           Algorithm          Type        Use_Case Complexity
0  Linear Regression    Supervised      Prediction        Low
1              Anand    Supervised  Classification     Medium
2                SVM    Supervised  Classification       High
3                KNN  Unsupervised  Classification     Medium
4      Random Forest    Supervised  Classification       High
5        Naive Bayes    Supervised  Classification        Low
6            K-Means  Unsupervised      Clustering     Medium
7     Neural Network    Supervised   Deep Learning  Very High

In [49]:
new_csv_ML.loc[[2,3,4],["Algorithm","Type"]]

       Algorithm          Type
2            SVM    Supervised
3            KNN  Unsupervised
4  Random Forest    Supervised

In [50]:
new_csv_ML.loc[:,["Algorithm","Type"]]

           Algorithm          Type
0  Linear Regression    Supervised
1              Anand    Supervised
2                SVM    Supervised
3                KNN  Unsupervised
4      Random Forest    Supervised
5        Naive Bayes    Supervised
6            K-Means  Unsupervised
7     Neural Network    Supervised

In [51]:
new_csv_ML.loc[[2,3,4],:]

       Algorithm          Type        Use_Case Complexity
2            SVM    Supervised  Classification       High
3            KNN  Unsupervised  Classification     Medium
4  Random Forest    Supervised  Classification       High

In [52]:
new_csv_ML.loc[[2],["Algorithm"]]

  Algorithm
2       SVM

In [53]:
new_csv_ML.iloc[2,1]

'Supervised'

In [54]:
new_csv_ML

           Algorithm          Type        Use_Case Complexity
0  Linear Regression    Supervised      Prediction        Low
1              Anand    Supervised  Classification     Medium
2                SVM    Supervised  Classification       High
3                KNN  Unsupervised  Classification     Medium
4      Random Forest    Supervised  Classification       High
5        Naive Bayes    Supervised  Classification        Low
6            K-Means  Unsupervised      Clustering     Medium
7     Neural Network    Supervised   Deep Learning  Very High

# dropna

In [66]:
raw_data = pd.read_csv("C:\\Users\\anand\\OneDrive\\Desktop\\ml-learning\\raw_data_students.csv")
raw_data

      ID   Name   Age       City  Score
0    1.0  LJQNM  32.0  Bangalore  66.15
1    2.0  OTRCJ  29.0      Delhi  73.92
2    3.0  NYAYB  30.0  Hyderabad  83.14
3    4.0  QYDTM  35.0     Mumbai  56.68
4    5.0  BXKCT  23.0    Chennai  69.24
5    6.0  YJOAY   NaN        NaN  83.74
6    7.0  LYZGH  18.0    Chennai  86.57
7    8.0  ODRMD  23.0     Mumbai  57.92
8    9.0  IBSQF  31.0     Mumbai  51.74
9   10.0  JOIPK  34.0    Chennai  52.61
10  11.0  NYJIZ   NaN        NaN  76.18
11  12.0  JZZUB  19.0    Chennai  64.61
12  13.0  OGLZJ  27.0  Bangalore  53.59
13  14.0  KLXTL  21.0  Bangalore  67.71
14  15.0  OZYDX  27.0  Bangalore  62.63
15  16.0  PGABU  21.0  Bangalore  78.16
16  17.0  SRSUZ  38.0    Chennai  79.51
17   NaN    NaN   NaN        NaN    NaN
18  19.0  EDEDZ  20.0  Bangalore  90.10
19  20.0  YBENN  27.0    Chennai  88.16

In [65]:
raw_data.dropna()

    ID   Name   Age       City  Score
0    1  LJQNM  32.0  Bangalore  66.15
1    2  OTRCJ  29.0      Delhi  73.92
2    3  NYAYB  30.0  Hyderabad  83.14
3    4  QYDTM  35.0     Mumbai  56.68
4    5  BXKCT  23.0    Chennai  69.24
6    7  LYZGH  18.0    Chennai  86.57
7    8  ODRMD  23.0     Mumbai  57.92
8    9  IBSQF  31.0     Mumbai  51.74
9   10  JOIPK  34.0    Chennai  52.61
11  12  JZZUB  19.0    Chennai  64.61
12  13  OGLZJ  27.0  Bangalore  53.59
13  14  KLXTL  21.0  Bangalore  67.71
14  15  OZYDX  27.0  Bangalore  62.63
15  16  PGABU  21.0  Bangalore  78.16
16  17  SRSUZ  38.0    Chennai  79.51
17  18  JJZLH  27.0      Delhi  86.55
18  19  EDEDZ  20.0  Bangalore  90.10
19  20  YBENN  27.0    Chennai  88.16

In [63]:
raw_data.dropna(axis=0)

    ID   Name   Age       City  Score
0    1  LJQNM  32.0  Bangalore  66.15
1    2  OTRCJ  29.0      Delhi  73.92
2    3  NYAYB  30.0  Hyderabad  83.14
3    4  QYDTM  35.0     Mumbai  56.68
4    5  BXKCT  23.0    Chennai  69.24
6    7  LYZGH  18.0    Chennai  86.57
7    8  ODRMD  23.0     Mumbai  57.92
8    9  IBSQF  31.0     Mumbai  51.74
9   10  JOIPK  34.0    Chennai  52.61
11  12  JZZUB  19.0    Chennai  64.61
12  13  OGLZJ  27.0  Bangalore  53.59
13  14  KLXTL  21.0  Bangalore  67.71
14  15  OZYDX  27.0  Bangalore  62.63
15  16  PGABU  21.0  Bangalore  78.16
16  17  SRSUZ  38.0    Chennai  79.51
17  18  JJZLH  27.0      Delhi  86.55
18  19  EDEDZ  20.0  Bangalore  90.10
19  20  YBENN  27.0    Chennai  88.16

In [64]:
raw_data.dropna(axis=1)

    ID   Name  Score
0    1  LJQNM  66.15
1    2  OTRCJ  73.92
2    3  NYAYB  83.14
3    4  QYDTM  56.68
4    5  BXKCT  69.24
5    6  YJOAY  83.74
6    7  LYZGH  86.57
7    8  ODRMD  57.92
8    9  IBSQF  51.74
9   10  JOIPK  52.61
10  11  NYJIZ  76.18
11  12  JZZUB  64.61
12  13  OGLZJ  53.59
13  14  KLXTL  67.71
14  15  OZYDX  62.63
15  16  PGABU  78.16
16  17  SRSUZ  79.51
17  18  JJZLH  86.55
18  19  EDEDZ  90.10
19  20  YBENN  88.16

In [68]:
raw_data = pd.read_csv("C:\\Users\\anand\\OneDrive\\Desktop\\ml-learning\\raw_data_students.csv")
raw_data

      ID   Name   Age       City  Score
0    1.0  LJQNM  32.0  Bangalore  66.15
1    2.0  OTRCJ  29.0      Delhi  73.92
2    3.0  NYAYB  30.0  Hyderabad  83.14
3    4.0  QYDTM  35.0     Mumbai  56.68
4    5.0  BXKCT  23.0    Chennai  69.24
5    6.0  YJOAY   NaN        NaN  83.74
6    7.0  LYZGH  18.0    Chennai  86.57
7    8.0  ODRMD  23.0     Mumbai  57.92
8    9.0  IBSQF  31.0     Mumbai  51.74
9   10.0  JOIPK  34.0    Chennai  52.61
10  11.0  NYJIZ   NaN        NaN  76.18
11  12.0  JZZUB  19.0    Chennai  64.61
12  13.0  OGLZJ  27.0  Bangalore  53.59
13  14.0  KLXTL  21.0  Bangalore  67.71
14  15.0  OZYDX  27.0  Bangalore  62.63
15  16.0  PGABU  21.0  Bangalore  78.16
16  17.0  SRSUZ  38.0    Chennai  79.51
17   NaN    NaN   NaN        NaN    NaN
18  19.0  EDEDZ  20.0  Bangalore  90.10
19  20.0  YBENN  27.0    Chennai  88.16

In [69]:
raw_data.dropna(how="all")

      ID   Name   Age       City  Score
0    1.0  LJQNM  32.0  Bangalore  66.15
1    2.0  OTRCJ  29.0      Delhi  73.92
2    3.0  NYAYB  30.0  Hyderabad  83.14
3    4.0  QYDTM  35.0     Mumbai  56.68
4    5.0  BXKCT  23.0    Chennai  69.24
5    6.0  YJOAY   NaN        NaN  83.74
6    7.0  LYZGH  18.0    Chennai  86.57
7    8.0  ODRMD  23.0     Mumbai  57.92
8    9.0  IBSQF  31.0     Mumbai  51.74
9   10.0  JOIPK  34.0    Chennai  52.61
10  11.0  NYJIZ   NaN        NaN  76.18
11  12.0  JZZUB  19.0    Chennai  64.61
12  13.0  OGLZJ  27.0  Bangalore  53.59
13  14.0  KLXTL  21.0  Bangalore  67.71
14  15.0  OZYDX  27.0  Bangalore  62.63
15  16.0  PGABU  21.0  Bangalore  78.16
16  17.0  SRSUZ  38.0    Chennai  79.51
18  19.0  EDEDZ  20.0  Bangalore  90.10
19  20.0  YBENN  27.0    Chennai  88.16

In [71]:
raw_data.dropna(how="any")

      ID   Name   Age       City  Score
0    1.0  LJQNM  32.0  Bangalore  66.15
1    2.0  OTRCJ  29.0      Delhi  73.92
2    3.0  NYAYB  30.0  Hyderabad  83.14
3    4.0  QYDTM  35.0     Mumbai  56.68
4    5.0  BXKCT  23.0    Chennai  69.24
6    7.0  LYZGH  18.0    Chennai  86.57
7    8.0  ODRMD  23.0     Mumbai  57.92
8    9.0  IBSQF  31.0     Mumbai  51.74
9   10.0  JOIPK  34.0    Chennai  52.61
11  12.0  JZZUB  19.0    Chennai  64.61
12  13.0  OGLZJ  27.0  Bangalore  53.59
13  14.0  KLXTL  21.0  Bangalore  67.71
14  15.0  OZYDX  27.0  Bangalore  62.63
15  16.0  PGABU  21.0  Bangalore  78.16
16  17.0  SRSUZ  38.0    Chennai  79.51
18  19.0  EDEDZ  20.0  Bangalore  90.10
19  20.0  YBENN  27.0    Chennai  88.16