# Series

In [111]:
import pandas as pd

a = [1,2,3,4]
var1 = pd.Series(a)

print(var1)

0    1
1    2
2    3
3    4
dtype: int64

In [112]:
b = [1,2,3,4]
var = pd.Series(b,dtype=float,index=['a','b','c','d'])
print(var)

a    1.0
b    2.0
c    3.0
d    4.0
dtype: float64

In [113]:
dic = {'Name':['Anand','Sanjay','Vaishu'],'RollNo':[65,56,57]}

var = pd.Series(dic)
print(var)

Name      [Anand, Sanjay, Vaishu]
RollNo               [65, 56, 57]
dtype: object

In [114]:
s = pd.Series(12,index=[1,2,3,4,5,6,7])
print(s)

1    12
2    12
3    12
4    12
5    12
6    12
7    12
dtype: int64

In [115]:
s1 = pd.Series(12,index=[1,2,3,4,5,6,7])
s2 = pd.Series(12,index=[1,2,3,4])
print(s1+s2)

1    24.0
2    24.0
3    24.0
4    24.0
5     NaN
6     NaN
7     NaN
dtype: float64

# DataFrame

In [116]:
l = [1,2,3,4,5,6]
var = pd.DataFrame(l)

print(var)
print(type(var))

   0
0  1
1  2
2  3
3  4
4  5
5  6
<class 'pandas.core.frame.DataFrame'>

In [117]:
a = {'a':[1,2,3,4,5],'b':[1,2,3,4,5]}

var = pd.DataFrame(a)

print(var)
print(type(var))

   a  b
0  1  1
1  2  2
2  3  3
3  4  4
4  5  5
<class 'pandas.core.frame.DataFrame'>

In [118]:
a = {'a':[1,2,3,4,5],'b':[1,2,3,4,5],65:[1,2,3,4,5]}

var = pd.DataFrame(a)

print(type(var))
print(var)

print(var['a'][2])

<class 'pandas.core.frame.DataFrame'>
   a  b  65
0  1  1   1
1  2  2   2
2  3  3   3
3  4  4   4
4  5  5   5
3

In [119]:
a = {'a':[1,2,3,4,5],'b':[1,2,3,4,5],65:[1,2,3,4,5]}

var = pd.DataFrame(a,columns=['b',65],index=['a','b','c','d','e'])

print(type(var))
print(var)

print(var['b'][0])

<class 'pandas.core.frame.DataFrame'>
   b  65
a  1   1
b  2   2
c  3   3
d  4   4
e  5   5
1

In [120]:
list = [[1,2,3,4,5],[6,7,8,9,10]]

var = pd.DataFrame(list)

print(var)

print(var[1][0])

   0  1  2  3   4
0  1  2  3  4   5
1  6  7  8  9  10
2

In [121]:
dic = {'a':pd.Series([1,2,3,4,5]),'b':pd.Series([6,7,8,9,10])}

var = pd.DataFrame(dic)

print(var)


print(var['a'][4])
print(var['b'][4])

   a   b
0  1   6
1  2   7
2  3   8
3  4   9
4  5  10
5
10

# Arthematic Operations

In [122]:
a = pd.DataFrame({"A":[1,2,3,4],"B":[5,6,7,8]})
a

   A  B
0  1  5
1  2  6
2  3  7
3  4  8

In [123]:
a["C"]=a["A"]+a["B"]
print(a)

   A  B   C
0  1  5   6
1  2  6   8
2  3  7  10
3  4  8  12

In [124]:
a["C"]=a["A"]-a["B"]
print(a)

   A  B  C
0  1  5 -4
1  2  6 -4
2  3  7 -4
3  4  8 -4

In [125]:
a["C"]=a["A"]*a["B"]
print(a)

   A  B   C
0  1  5   5
1  2  6  12
2  3  7  21
3  4  8  32

In [126]:
a["C"]=a["A"]/a["B"]
print(a)

   A  B         C
0  1  5  0.200000
1  2  6  0.333333
2  3  7  0.428571
3  4  8  0.500000

In [127]:
a["C"]=a["A"]%a["B"]
print(a)

   A  B  C
0  1  5  1
1  2  6  2
2  3  7  3
3  4  8  4

In [128]:
a["Java"]=a["A"]>2
a["Python"]=a["B"]>5
print(a)

   A  B  C   Java  Python
0  1  5  1  False   False
1  2  6  2  False    True
2  3  7  3   True    True
3  4  8  4   True    True

# Insert

In [129]:
b = pd.DataFrame({"A":[1,2,3,4,5],"B":[9,8,7,6,5]})
b

   A  B
0  1  9
1  2  8
2  3  7
3  4  6
4  5  5

In [130]:
# b.insert()  there will be 3 parameters... 1st is index number 2nd is name of column and 3rd is the data which is to be printed
b.insert(1,"C",[6,3,7,6,5])
b.insert(0,"Anand",b["A"])
print(b)

   Anand  A  C  B
0      1  1  6  9
1      2  2  3  8
2      3  3  7  7
3      4  4  6  6
4      5  5  5  5

In [131]:
b["D"] = b["A"][:3]
b

   Anand  A  C  B    D
0      1  1  6  9  1.0
1      2  2  3  8  2.0
2      3  3  7  7  3.0
3      4  4  6  6  NaN
4      5  5  5  5  NaN

# Delete

In [132]:
deleted_column = b.pop('B')
print(b)
deleted_column
print(deleted_column)

   Anand  A  C    D
0      1  1  6  1.0
1      2  2  3  2.0
2      3  3  7  3.0
3      4  4  6  NaN
4      5  5  5  NaN
0    9
1    8
2    7
3    6
4    5
Name: B, dtype: int64

# Write CSV

In [133]:
dic = {"A":[1,2,3,4,5,6],"B":[6,5,4,3,2,1],"C":[3,1,4,2,6,5]}

d = pd.DataFrame(dic)

print(d)

d.to_csv("Basic_csv_file.csv",index=False)

   A  B  C
0  1  6  3
1  2  5  1
2  3  4  4
3  4  3  2
4  5  2  6
5  6  1  5

# Read CSV

In [134]:
new_csv_ML = pd.read_csv("C:\\Users\\anand\\OneDrive\\Desktop\\ml-learning\\pandas\\machine_learning_data.csv")
print(new_csv_ML)

           Algorithm          Type        Use_Case Complexity
0  Linear Regression    Supervised      Prediction        Low
1      Decision Tree    Supervised  Classification     Medium
2                SVM    Supervised  Classification       High
3                KNN    Supervised  Classification     Medium
4      Random Forest    Supervised  Classification       High
5        Naive Bayes    Supervised  Classification        Low
6            K-Means  Unsupervised      Clustering     Medium
7     Neural Network    Supervised   Deep Learning  Very High

In [135]:
new_csv_ML = pd.read_csv("C:\\Users\\anand\\OneDrive\\Desktop\\ml-learning\\pandas\\machine_learning_data.csv",nrows=3)
print(new_csv_ML) #print number of rows

           Algorithm        Type        Use_Case Complexity
0  Linear Regression  Supervised      Prediction        Low
1      Decision Tree  Supervised  Classification     Medium
2                SVM  Supervised  Classification       High

In [136]:
new_csv_ML = pd.read_csv("C:\\Users\\anand\\OneDrive\\Desktop\\ml-learning\\pandas\\machine_learning_data.csv",usecols = ["Algorithm","Complexity"])
new_csv_ML #remove columns using names

           Algorithm Complexity
0  Linear Regression        Low
1      Decision Tree     Medium
2                SVM       High
3                KNN     Medium
4      Random Forest       High
5        Naive Bayes        Low
6            K-Means     Medium
7     Neural Network  Very High

In [137]:
new_csv_ML = pd.read_csv("C:\\Users\\anand\\OneDrive\\Desktop\\ml-learning\\pandas\\machine_learning_data.csv",usecols = [2,3])
new_csv_ML #remove specifix columns using indexes

         Use_Case Complexity
0      Prediction        Low
1  Classification     Medium
2  Classification       High
3  Classification     Medium
4  Classification       High
5  Classification        Low
6      Clustering     Medium
7   Deep Learning  Very High

In [138]:
new_csv_ML = pd.read_csv("C:\\Users\\anand\\OneDrive\\Desktop\\ml-learning\\pandas\\machine_learning_data.csv",skiprows=2)
new_csv_ML #skip first 2 rows

    Decision Tree    Supervised  Classification     Medium
0             SVM    Supervised  Classification       High
1             KNN    Supervised  Classification     Medium
2   Random Forest    Supervised  Classification       High
3     Naive Bayes    Supervised  Classification        Low
4         K-Means  Unsupervised      Clustering     Medium
5  Neural Network    Supervised   Deep Learning  Very High

In [139]:
new_csv_ML = pd.read_csv("C:\\Users\\anand\\OneDrive\\Desktop\\ml-learning\\pandas\\machine_learning_data.csv",skiprows=[0,3,4])
new_csv_ML #skip rows

  Linear Regression    Supervised      Prediction        Low
0     Decision Tree    Supervised  Classification     Medium
1     Random Forest    Supervised  Classification       High
2       Naive Bayes    Supervised  Classification        Low
3           K-Means  Unsupervised      Clustering     Medium
4    Neural Network    Supervised   Deep Learning  Very High

In [140]:
new_csv_ML = pd.read_csv("C:\\Users\\anand\\OneDrive\\Desktop\\ml-learning\\pandas\\machine_learning_data.csv")
new_csv_ML.columns = ["Algorithm","Type","Category","Complexcity"]
new_csv_ML

           Algorithm          Type        Category Complexcity
0  Linear Regression    Supervised      Prediction         Low
1      Decision Tree    Supervised  Classification      Medium
2                SVM    Supervised  Classification        High
3                KNN    Supervised  Classification      Medium
4      Random Forest    Supervised  Classification        High
5        Naive Bayes    Supervised  Classification         Low
6            K-Means  Unsupervised      Clustering      Medium
7     Neural Network    Supervised   Deep Learning   Very High

In [141]:
new_csv_ML = pd.read_csv("C:\\Users\\anand\\OneDrive\\Desktop\\ml-learning\\pandas\\machine_learning_data.csv",index_col = "Algorithm")
new_csv_ML # make the required column as index

                           Type        Use_Case Complexity
Algorithm
Linear Regression    Supervised      Prediction        Low
Decision Tree        Supervised  Classification     Medium
SVM                  Supervised  Classification       High
KNN                  Supervised  Classification     Medium
Random Forest        Supervised  Classification       High
Naive Bayes          Supervised  Classification        Low
K-Means            Unsupervised      Clustering     Medium
Neural Network       Supervised   Deep Learning  Very High

In [142]:
new_csv_ML = pd.read_csv("C:\\Users\\anand\\OneDrive\\Desktop\\ml-learning\\pandas\\machine_learning_data.csv",header = 4)
new_csv_ML #first 4 rows data

              KNN    Supervised  Classification     Medium
0   Random Forest    Supervised  Classification       High
1     Naive Bayes    Supervised  Classification        Low
2         K-Means  Unsupervised      Clustering     Medium
3  Neural Network    Supervised   Deep Learning  Very High

In [143]:
new_csv_ML = pd.read_csv("C:\\Users\\anand\\OneDrive\\Desktop\\ml-learning\\pandas\\machine_learning_data.csv",names = ["anand","vaishu","sanjay","vinay"])
new_csv_ML #change columns names to required column names

               anand        vaishu          sanjay       vinay
0          Algorithm          Type        Use_Case  Complexity
1  Linear Regression    Supervised      Prediction         Low
2      Decision Tree    Supervised  Classification      Medium
3                SVM    Supervised  Classification        High
4                KNN    Supervised  Classification      Medium
5      Random Forest    Supervised  Classification        High
6        Naive Bayes    Supervised  Classification         Low
7            K-Means  Unsupervised      Clustering      Medium
8     Neural Network    Supervised   Deep Learning   Very High

In [144]:
new_csv_ML = pd.read_csv("C:\\Users\\anand\\OneDrive\\Desktop\\ml-learning\\pandas\\machine_learning_data.csv",header = None,prefix = "columns")
new_csv_ML #change the column names to below

            columns0      columns1        columns2    columns3
0          Algorithm          Type        Use_Case  Complexity
1  Linear Regression    Supervised      Prediction         Low
2      Decision Tree    Supervised  Classification      Medium
3                SVM    Supervised  Classification        High
4                KNN    Supervised  Classification      Medium
5      Random Forest    Supervised  Classification        High
6        Naive Bayes    Supervised  Classification         Low
7            K-Means  Unsupervised      Clustering      Medium
8     Neural Network    Supervised   Deep Learning   Very High

In [145]:
new_csv_ML = pd.read_csv("C:\\Users\\anand\\OneDrive\\Desktop\\ml-learning\\pandas\\machine_learning_data.csv")
new_csv_ML

           Algorithm          Type        Use_Case Complexity
0  Linear Regression    Supervised      Prediction        Low
1      Decision Tree    Supervised  Classification     Medium
2                SVM    Supervised  Classification       High
3                KNN    Supervised  Classification     Medium
4      Random Forest    Supervised  Classification       High
5        Naive Bayes    Supervised  Classification        Low
6            K-Means  Unsupervised      Clustering     Medium
7     Neural Network    Supervised   Deep Learning  Very High

# Pandas Functions

In [146]:
new_csv_ML.index #indexes

RangeIndex(start=0, stop=8, step=1)

In [147]:
new_csv_ML.columns #names of the coulmns

Index(['Algorithm', 'Type', 'Use_Case', 'Complexity'], dtype='object')

In [148]:
new_csv_ML.describe() #describing the data

                Algorithm        Type        Use_Case Complexity
count                   8           8               8          8
unique                  8           2               4          4
top     Linear Regression  Supervised  Classification     Medium
freq                    1           7               5          3

In [149]:
new_csv_ML.head(4) # data of first 4 rows

           Algorithm        Type        Use_Case Complexity
0  Linear Regression  Supervised      Prediction        Low
1      Decision Tree  Supervised  Classification     Medium
2                SVM  Supervised  Classification       High
3                KNN  Supervised  Classification     Medium

In [150]:
new_csv_ML.tail(2) #data of last 2 rows

        Algorithm          Type       Use_Case Complexity
6         K-Means  Unsupervised     Clustering     Medium
7  Neural Network    Supervised  Deep Learning  Very High

In [151]:
new_csv_ML[2:5] #data from 2 to 5 rows

       Algorithm        Type        Use_Case Complexity
2            SVM  Supervised  Classification       High
3            KNN  Supervised  Classification     Medium
4  Random Forest  Supervised  Classification       High

In [152]:
new_csv_ML.index.array #storing index values as array

<PandasArray>
[0, 1, 2, 3, 4, 5, 6, 7]
Length: 8, dtype: int64

In [153]:
new_csv_ML.to_numpy() #convert to numpy

array([['Linear Regression', 'Supervised', 'Prediction', 'Low'],
       ['Decision Tree', 'Supervised', 'Classification', 'Medium'],
       ['SVM', 'Supervised', 'Classification', 'High'],
       ['KNN', 'Supervised', 'Classification', 'Medium'],
       ['Random Forest', 'Supervised', 'Classification', 'High'],
       ['Naive Bayes', 'Supervised', 'Classification', 'Low'],
       ['K-Means', 'Unsupervised', 'Clustering', 'Medium'],
       ['Neural Network', 'Supervised', 'Deep Learning', 'Very High']],
      dtype=object)

In [154]:
print(type(new_csv_ML))

<class 'pandas.core.frame.DataFrame'>

In [155]:
import numpy as np
a = np.asarray(new_csv_ML) #convert to numpy
a

array([['Linear Regression', 'Supervised', 'Prediction', 'Low'],
       ['Decision Tree', 'Supervised', 'Classification', 'Medium'],
       ['SVM', 'Supervised', 'Classification', 'High'],
       ['KNN', 'Supervised', 'Classification', 'Medium'],
       ['Random Forest', 'Supervised', 'Classification', 'High'],
       ['Naive Bayes', 'Supervised', 'Classification', 'Low'],
       ['K-Means', 'Unsupervised', 'Clustering', 'Medium'],
       ['Neural Network', 'Supervised', 'Deep Learning', 'Very High']],
      dtype=object)

In [156]:
new_csv_ML.sort_index(axis=0,ascending=False) #reverse the data

           Algorithm          Type        Use_Case Complexity
7     Neural Network    Supervised   Deep Learning  Very High
6            K-Means  Unsupervised      Clustering     Medium
5        Naive Bayes    Supervised  Classification        Low
4      Random Forest    Supervised  Classification       High
3                KNN    Supervised  Classification     Medium
2                SVM    Supervised  Classification       High
1      Decision Tree    Supervised  Classification     Medium
0  Linear Regression    Supervised      Prediction        Low

In [157]:
new_csv_ML["Algorithm"][1] = "Anand"
new_csv_ML

           Algorithm          Type        Use_Case Complexity
0  Linear Regression    Supervised      Prediction        Low
1              Anand    Supervised  Classification     Medium
2                SVM    Supervised  Classification       High
3                KNN    Supervised  Classification     Medium
4      Random Forest    Supervised  Classification       High
5        Naive Bayes    Supervised  Classification        Low
6            K-Means  Unsupervised      Clustering     Medium
7     Neural Network    Supervised   Deep Learning  Very High

In [158]:
new_csv_ML.loc[3,"Type"] = "Unsupervised" #change data of a particular row and column
new_csv_ML

           Algorithm          Type        Use_Case Complexity
0  Linear Regression    Supervised      Prediction        Low
1              Anand    Supervised  Classification     Medium
2                SVM    Supervised  Classification       High
3                KNN  Unsupervised  Classification     Medium
4      Random Forest    Supervised  Classification       High
5        Naive Bayes    Supervised  Classification        Low
6            K-Means  Unsupervised      Clustering     Medium
7     Neural Network    Supervised   Deep Learning  Very High

In [159]:
new_csv_ML.loc[[2,3,4],["Algorithm","Type"]] #data of particular rows and coulmns

       Algorithm          Type
2            SVM    Supervised
3            KNN  Unsupervised
4  Random Forest    Supervised

In [160]:
new_csv_ML.loc[:,["Algorithm","Type"]] #all rows with particular columns

           Algorithm          Type
0  Linear Regression    Supervised
1              Anand    Supervised
2                SVM    Supervised
3                KNN  Unsupervised
4      Random Forest    Supervised
5        Naive Bayes    Supervised
6            K-Means  Unsupervised
7     Neural Network    Supervised

In [161]:
new_csv_ML.loc[[2,3,4],:] #all coulmns with particular row

       Algorithm          Type        Use_Case Complexity
2            SVM    Supervised  Classification       High
3            KNN  Unsupervised  Classification     Medium
4  Random Forest    Supervised  Classification       High

In [162]:
new_csv_ML.loc[[2],["Algorithm"]] #data of particular row and particular column

  Algorithm
2       SVM

In [163]:
new_csv_ML.iloc[2,1] #data of particular row and coulmn

'Supervised'

In [164]:
new_csv_ML

           Algorithm          Type        Use_Case Complexity
0  Linear Regression    Supervised      Prediction        Low
1              Anand    Supervised  Classification     Medium
2                SVM    Supervised  Classification       High
3                KNN  Unsupervised  Classification     Medium
4      Random Forest    Supervised  Classification       High
5        Naive Bayes    Supervised  Classification        Low
6            K-Means  Unsupervised      Clustering     Medium
7     Neural Network    Supervised   Deep Learning  Very High

# dropna

In [165]:
raw_data = pd.read_csv("C:\\Users\\anand\\OneDrive\\Desktop\\ml-learning\\pandas\\raw_data_students.csv")
raw_data

      ID   Name   Age       City  Score
0    1.0  LJQNM  32.0  Bangalore  66.15
1    2.0  OTRCJ  29.0      Delhi  73.92
2    3.0  NYAYB  30.0  Hyderabad  83.14
3    4.0  QYDTM  35.0     Mumbai  56.68
4    5.0  BXKCT  23.0    Chennai  69.24
5    6.0  YJOAY   NaN        NaN  83.74
6    7.0  LYZGH  18.0    Chennai  86.57
7    8.0  ODRMD  23.0     Mumbai  57.92
8    9.0  IBSQF  31.0     Mumbai  51.74
9   10.0  JOIPK  34.0    Chennai  52.61
10  11.0  NYJIZ   NaN        NaN  76.18
11  12.0  JZZUB  19.0    Chennai  64.61
12  13.0  OGLZJ  27.0  Bangalore  53.59
13  14.0  KLXTL  21.0  Bangalore  67.71
14  15.0  OZYDX  27.0  Bangalore  62.63
15  16.0  PGABU  21.0  Bangalore  78.16
16  17.0  SRSUZ  38.0    Chennai  79.51
17   NaN    NaN   NaN        NaN    NaN
18  19.0  EDEDZ  20.0  Bangalore  90.10
19  20.0  YBENN  27.0    Chennai  88.16

In [166]:
raw_data.dropna() #removes rows or column having null values

      ID   Name   Age       City  Score
0    1.0  LJQNM  32.0  Bangalore  66.15
1    2.0  OTRCJ  29.0      Delhi  73.92
2    3.0  NYAYB  30.0  Hyderabad  83.14
3    4.0  QYDTM  35.0     Mumbai  56.68
4    5.0  BXKCT  23.0    Chennai  69.24
6    7.0  LYZGH  18.0    Chennai  86.57
7    8.0  ODRMD  23.0     Mumbai  57.92
8    9.0  IBSQF  31.0     Mumbai  51.74
9   10.0  JOIPK  34.0    Chennai  52.61
11  12.0  JZZUB  19.0    Chennai  64.61
12  13.0  OGLZJ  27.0  Bangalore  53.59
13  14.0  KLXTL  21.0  Bangalore  67.71
14  15.0  OZYDX  27.0  Bangalore  62.63
15  16.0  PGABU  21.0  Bangalore  78.16
16  17.0  SRSUZ  38.0    Chennai  79.51
18  19.0  EDEDZ  20.0  Bangalore  90.10
19  20.0  YBENN  27.0    Chennai  88.16

In [167]:
raw_data.dropna(axis=0) #removes rows with null values

      ID   Name   Age       City  Score
0    1.0  LJQNM  32.0  Bangalore  66.15
1    2.0  OTRCJ  29.0      Delhi  73.92
2    3.0  NYAYB  30.0  Hyderabad  83.14
3    4.0  QYDTM  35.0     Mumbai  56.68
4    5.0  BXKCT  23.0    Chennai  69.24
6    7.0  LYZGH  18.0    Chennai  86.57
7    8.0  ODRMD  23.0     Mumbai  57.92
8    9.0  IBSQF  31.0     Mumbai  51.74
9   10.0  JOIPK  34.0    Chennai  52.61
11  12.0  JZZUB  19.0    Chennai  64.61
12  13.0  OGLZJ  27.0  Bangalore  53.59
13  14.0  KLXTL  21.0  Bangalore  67.71
14  15.0  OZYDX  27.0  Bangalore  62.63
15  16.0  PGABU  21.0  Bangalore  78.16
16  17.0  SRSUZ  38.0    Chennai  79.51
18  19.0  EDEDZ  20.0  Bangalore  90.10
19  20.0  YBENN  27.0    Chennai  88.16

In [168]:
raw_data.dropna(axis=1) #removes columns with null values

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [169]:
raw_data = pd.read_csv("C:\\Users\\anand\\OneDrive\\Desktop\\ml-learning\\pandas\\raw_data_students.csv")
raw_data

      ID   Name   Age       City  Score
0    1.0  LJQNM  32.0  Bangalore  66.15
1    2.0  OTRCJ  29.0      Delhi  73.92
2    3.0  NYAYB  30.0  Hyderabad  83.14
3    4.0  QYDTM  35.0     Mumbai  56.68
4    5.0  BXKCT  23.0    Chennai  69.24
5    6.0  YJOAY   NaN        NaN  83.74
6    7.0  LYZGH  18.0    Chennai  86.57
7    8.0  ODRMD  23.0     Mumbai  57.92
8    9.0  IBSQF  31.0     Mumbai  51.74
9   10.0  JOIPK  34.0    Chennai  52.61
10  11.0  NYJIZ   NaN        NaN  76.18
11  12.0  JZZUB  19.0    Chennai  64.61
12  13.0  OGLZJ  27.0  Bangalore  53.59
13  14.0  KLXTL  21.0  Bangalore  67.71
14  15.0  OZYDX  27.0  Bangalore  62.63
15  16.0  PGABU  21.0  Bangalore  78.16
16  17.0  SRSUZ  38.0    Chennai  79.51
17   NaN    NaN   NaN        NaN    NaN
18  19.0  EDEDZ  20.0  Bangalore  90.10
19  20.0  YBENN  27.0    Chennai  88.16

In [170]:
raw_data.dropna(how="all") #removes rows with all the values = null

      ID   Name   Age       City  Score
0    1.0  LJQNM  32.0  Bangalore  66.15
1    2.0  OTRCJ  29.0      Delhi  73.92
2    3.0  NYAYB  30.0  Hyderabad  83.14
3    4.0  QYDTM  35.0     Mumbai  56.68
4    5.0  BXKCT  23.0    Chennai  69.24
5    6.0  YJOAY   NaN        NaN  83.74
6    7.0  LYZGH  18.0    Chennai  86.57
7    8.0  ODRMD  23.0     Mumbai  57.92
8    9.0  IBSQF  31.0     Mumbai  51.74
9   10.0  JOIPK  34.0    Chennai  52.61
10  11.0  NYJIZ   NaN        NaN  76.18
11  12.0  JZZUB  19.0    Chennai  64.61
12  13.0  OGLZJ  27.0  Bangalore  53.59
13  14.0  KLXTL  21.0  Bangalore  67.71
14  15.0  OZYDX  27.0  Bangalore  62.63
15  16.0  PGABU  21.0  Bangalore  78.16
16  17.0  SRSUZ  38.0    Chennai  79.51
18  19.0  EDEDZ  20.0  Bangalore  90.10
19  20.0  YBENN  27.0    Chennai  88.16

In [171]:
raw_data.dropna(how="any") #removes all the rows with null values

      ID   Name   Age       City  Score
0    1.0  LJQNM  32.0  Bangalore  66.15
1    2.0  OTRCJ  29.0      Delhi  73.92
2    3.0  NYAYB  30.0  Hyderabad  83.14
3    4.0  QYDTM  35.0     Mumbai  56.68
4    5.0  BXKCT  23.0    Chennai  69.24
6    7.0  LYZGH  18.0    Chennai  86.57
7    8.0  ODRMD  23.0     Mumbai  57.92
8    9.0  IBSQF  31.0     Mumbai  51.74
9   10.0  JOIPK  34.0    Chennai  52.61
11  12.0  JZZUB  19.0    Chennai  64.61
12  13.0  OGLZJ  27.0  Bangalore  53.59
13  14.0  KLXTL  21.0  Bangalore  67.71
14  15.0  OZYDX  27.0  Bangalore  62.63
15  16.0  PGABU  21.0  Bangalore  78.16
16  17.0  SRSUZ  38.0    Chennai  79.51
18  19.0  EDEDZ  20.0  Bangalore  90.10
19  20.0  YBENN  27.0    Chennai  88.16

In [172]:
raw_data.dropna(subset=["Age"]) #removes null data from column

      ID   Name   Age       City  Score
0    1.0  LJQNM  32.0  Bangalore  66.15
1    2.0  OTRCJ  29.0      Delhi  73.92
2    3.0  NYAYB  30.0  Hyderabad  83.14
3    4.0  QYDTM  35.0     Mumbai  56.68
4    5.0  BXKCT  23.0    Chennai  69.24
6    7.0  LYZGH  18.0    Chennai  86.57
7    8.0  ODRMD  23.0     Mumbai  57.92
8    9.0  IBSQF  31.0     Mumbai  51.74
9   10.0  JOIPK  34.0    Chennai  52.61
11  12.0  JZZUB  19.0    Chennai  64.61
12  13.0  OGLZJ  27.0  Bangalore  53.59
13  14.0  KLXTL  21.0  Bangalore  67.71
14  15.0  OZYDX  27.0  Bangalore  62.63
15  16.0  PGABU  21.0  Bangalore  78.16
16  17.0  SRSUZ  38.0    Chennai  79.51
18  19.0  EDEDZ  20.0  Bangalore  90.10
19  20.0  YBENN  27.0    Chennai  88.16

In [173]:
# raw_data.dropna(inplace = True)
# raw_data

In [174]:
# raw_data.drop(thresh = 1)
# removes the data with 1 null values if i change the number the count of all values changes

In [175]:
raw_data.fillna("anand|") #add anand| in place of null data

        ID    Name     Age       City   Score
0      1.0   LJQNM    32.0  Bangalore   66.15
1      2.0   OTRCJ    29.0      Delhi   73.92
2      3.0   NYAYB    30.0  Hyderabad   83.14
3      4.0   QYDTM    35.0     Mumbai   56.68
4      5.0   BXKCT    23.0    Chennai   69.24
5      6.0   YJOAY  anand|     anand|   83.74
6      7.0   LYZGH    18.0    Chennai   86.57
7      8.0   ODRMD    23.0     Mumbai   57.92
8      9.0   IBSQF    31.0     Mumbai   51.74
9     10.0   JOIPK    34.0    Chennai   52.61
10    11.0   NYJIZ  anand|     anand|   76.18
11    12.0   JZZUB    19.0    Chennai   64.61
12    13.0   OGLZJ    27.0  Bangalore   53.59
13    14.0   KLXTL    21.0  Bangalore   67.71
14    15.0   OZYDX    27.0  Bangalore   62.63
15    16.0   PGABU    21.0  Bangalore   78.16
16    17.0   SRSUZ    38.0    Chennai   79.51
17  anand|  anand|  anand|     anand|  anand|
18    19.0   EDEDZ    20.0  Bangalore    90.1
19    20.0   YBENN    27.0    Chennai   88.16

In [176]:
raw_data.fillna({"Age":"anand"}) #add anand in place of null values present in column age

      ID   Name    Age       City  Score
0    1.0  LJQNM   32.0  Bangalore  66.15
1    2.0  OTRCJ   29.0      Delhi  73.92
2    3.0  NYAYB   30.0  Hyderabad  83.14
3    4.0  QYDTM   35.0     Mumbai  56.68
4    5.0  BXKCT   23.0    Chennai  69.24
5    6.0  YJOAY  anand        NaN  83.74
6    7.0  LYZGH   18.0    Chennai  86.57
7    8.0  ODRMD   23.0     Mumbai  57.92
8    9.0  IBSQF   31.0     Mumbai  51.74
9   10.0  JOIPK   34.0    Chennai  52.61
10  11.0  NYJIZ  anand        NaN  76.18
11  12.0  JZZUB   19.0    Chennai  64.61
12  13.0  OGLZJ   27.0  Bangalore  53.59
13  14.0  KLXTL   21.0  Bangalore  67.71
14  15.0  OZYDX   27.0  Bangalore  62.63
15  16.0  PGABU   21.0  Bangalore  78.16
16  17.0  SRSUZ   38.0    Chennai  79.51
17   NaN    NaN  anand        NaN    NaN
18  19.0  EDEDZ   20.0  Bangalore  90.10
19  20.0  YBENN   27.0    Chennai  88.16

In [177]:
raw_data.fillna(method="ffill") #fill data from previous data as columns

      ID   Name   Age       City  Score
0    1.0  LJQNM  32.0  Bangalore  66.15
1    2.0  OTRCJ  29.0      Delhi  73.92
2    3.0  NYAYB  30.0  Hyderabad  83.14
3    4.0  QYDTM  35.0     Mumbai  56.68
4    5.0  BXKCT  23.0    Chennai  69.24
5    6.0  YJOAY  23.0    Chennai  83.74
6    7.0  LYZGH  18.0    Chennai  86.57
7    8.0  ODRMD  23.0     Mumbai  57.92
8    9.0  IBSQF  31.0     Mumbai  51.74
9   10.0  JOIPK  34.0    Chennai  52.61
10  11.0  NYJIZ  34.0    Chennai  76.18
11  12.0  JZZUB  19.0    Chennai  64.61
12  13.0  OGLZJ  27.0  Bangalore  53.59
13  14.0  KLXTL  21.0  Bangalore  67.71
14  15.0  OZYDX  27.0  Bangalore  62.63
15  16.0  PGABU  21.0  Bangalore  78.16
16  17.0  SRSUZ  38.0    Chennai  79.51
17  17.0  SRSUZ  38.0    Chennai  79.51
18  19.0  EDEDZ  20.0  Bangalore  90.10
19  20.0  YBENN  27.0    Chennai  88.16

In [178]:
raw_data.fillna(method="bfill") #fill data from next data as columns

      ID   Name   Age       City  Score
0    1.0  LJQNM  32.0  Bangalore  66.15
1    2.0  OTRCJ  29.0      Delhi  73.92
2    3.0  NYAYB  30.0  Hyderabad  83.14
3    4.0  QYDTM  35.0     Mumbai  56.68
4    5.0  BXKCT  23.0    Chennai  69.24
5    6.0  YJOAY  18.0    Chennai  83.74
6    7.0  LYZGH  18.0    Chennai  86.57
7    8.0  ODRMD  23.0     Mumbai  57.92
8    9.0  IBSQF  31.0     Mumbai  51.74
9   10.0  JOIPK  34.0    Chennai  52.61
10  11.0  NYJIZ  19.0    Chennai  76.18
11  12.0  JZZUB  19.0    Chennai  64.61
12  13.0  OGLZJ  27.0  Bangalore  53.59
13  14.0  KLXTL  21.0  Bangalore  67.71
14  15.0  OZYDX  27.0  Bangalore  62.63
15  16.0  PGABU  21.0  Bangalore  78.16
16  17.0  SRSUZ  38.0    Chennai  79.51
17  19.0  EDEDZ  20.0  Bangalore  90.10
18  19.0  EDEDZ  20.0  Bangalore  90.10
19  20.0  YBENN  27.0    Chennai  88.16

In [179]:
raw_data.fillna(method="ffill",axis = 1) #fill data from previous data as rows

      ID   Name    Age       City  Score
0    1.0  LJQNM   32.0  Bangalore  66.15
1    2.0  OTRCJ   29.0      Delhi  73.92
2    3.0  NYAYB   30.0  Hyderabad  83.14
3    4.0  QYDTM   35.0     Mumbai  56.68
4    5.0  BXKCT   23.0    Chennai  69.24
5    6.0  YJOAY  YJOAY      YJOAY  83.74
6    7.0  LYZGH   18.0    Chennai  86.57
7    8.0  ODRMD   23.0     Mumbai  57.92
8    9.0  IBSQF   31.0     Mumbai  51.74
9   10.0  JOIPK   34.0    Chennai  52.61
10  11.0  NYJIZ  NYJIZ      NYJIZ  76.18
11  12.0  JZZUB   19.0    Chennai  64.61
12  13.0  OGLZJ   27.0  Bangalore  53.59
13  14.0  KLXTL   21.0  Bangalore  67.71
14  15.0  OZYDX   27.0  Bangalore  62.63
15  16.0  PGABU   21.0  Bangalore  78.16
16  17.0  SRSUZ   38.0    Chennai  79.51
17   NaN    NaN    NaN        NaN    NaN
18  19.0  EDEDZ   20.0  Bangalore   90.1
19  20.0  YBENN   27.0    Chennai  88.16

In [180]:
raw_data.fillna(method="ffill",axis = 1) #fill data from previous data as rows

      ID   Name    Age       City  Score
0    1.0  LJQNM   32.0  Bangalore  66.15
1    2.0  OTRCJ   29.0      Delhi  73.92
2    3.0  NYAYB   30.0  Hyderabad  83.14
3    4.0  QYDTM   35.0     Mumbai  56.68
4    5.0  BXKCT   23.0    Chennai  69.24
5    6.0  YJOAY  YJOAY      YJOAY  83.74
6    7.0  LYZGH   18.0    Chennai  86.57
7    8.0  ODRMD   23.0     Mumbai  57.92
8    9.0  IBSQF   31.0     Mumbai  51.74
9   10.0  JOIPK   34.0    Chennai  52.61
10  11.0  NYJIZ  NYJIZ      NYJIZ  76.18
11  12.0  JZZUB   19.0    Chennai  64.61
12  13.0  OGLZJ   27.0  Bangalore  53.59
13  14.0  KLXTL   21.0  Bangalore  67.71
14  15.0  OZYDX   27.0  Bangalore  62.63
15  16.0  PGABU   21.0  Bangalore  78.16
16  17.0  SRSUZ   38.0    Chennai  79.51
17   NaN    NaN    NaN        NaN    NaN
18  19.0  EDEDZ   20.0  Bangalore   90.1
19  20.0  YBENN   27.0    Chennai  88.16

In [181]:
# raw_data.fillna(1,implace=True)
# replace all the null values with 1 permanently

In [182]:
raw_data

      ID   Name   Age       City  Score
0    1.0  LJQNM  32.0  Bangalore  66.15
1    2.0  OTRCJ  29.0      Delhi  73.92
2    3.0  NYAYB  30.0  Hyderabad  83.14
3    4.0  QYDTM  35.0     Mumbai  56.68
4    5.0  BXKCT  23.0    Chennai  69.24
5    6.0  YJOAY   NaN        NaN  83.74
6    7.0  LYZGH  18.0    Chennai  86.57
7    8.0  ODRMD  23.0     Mumbai  57.92
8    9.0  IBSQF  31.0     Mumbai  51.74
9   10.0  JOIPK  34.0    Chennai  52.61
10  11.0  NYJIZ   NaN        NaN  76.18
11  12.0  JZZUB  19.0    Chennai  64.61
12  13.0  OGLZJ  27.0  Bangalore  53.59
13  14.0  KLXTL  21.0  Bangalore  67.71
14  15.0  OZYDX  27.0  Bangalore  62.63
15  16.0  PGABU  21.0  Bangalore  78.16
16  17.0  SRSUZ  38.0    Chennai  79.51
17   NaN    NaN   NaN        NaN    NaN
18  19.0  EDEDZ  20.0  Bangalore  90.10
19  20.0  YBENN  27.0    Chennai  88.16

In [183]:
raw_data.fillna("anand",limit =2)

       ID   Name    Age       City  Score
0     1.0  LJQNM   32.0  Bangalore  66.15
1     2.0  OTRCJ   29.0      Delhi  73.92
2     3.0  NYAYB   30.0  Hyderabad  83.14
3     4.0  QYDTM   35.0     Mumbai  56.68
4     5.0  BXKCT   23.0    Chennai  69.24
5     6.0  YJOAY  anand      anand  83.74
6     7.0  LYZGH   18.0    Chennai  86.57
7     8.0  ODRMD   23.0     Mumbai  57.92
8     9.0  IBSQF   31.0     Mumbai  51.74
9    10.0  JOIPK   34.0    Chennai  52.61
10   11.0  NYJIZ  anand      anand  76.18
11   12.0  JZZUB   19.0    Chennai  64.61
12   13.0  OGLZJ   27.0  Bangalore  53.59
13   14.0  KLXTL   21.0  Bangalore  67.71
14   15.0  OZYDX   27.0  Bangalore  62.63
15   16.0  PGABU   21.0  Bangalore  78.16
16   17.0  SRSUZ   38.0    Chennai  79.51
17  anand  anand    NaN        NaN  anand
18   19.0  EDEDZ   20.0  Bangalore   90.1
19   20.0  YBENN   27.0    Chennai  88.16

# Replace

In [184]:
raw_data

      ID   Name   Age       City  Score
0    1.0  LJQNM  32.0  Bangalore  66.15
1    2.0  OTRCJ  29.0      Delhi  73.92
2    3.0  NYAYB  30.0  Hyderabad  83.14
3    4.0  QYDTM  35.0     Mumbai  56.68
4    5.0  BXKCT  23.0    Chennai  69.24
5    6.0  YJOAY   NaN        NaN  83.74
6    7.0  LYZGH  18.0    Chennai  86.57
7    8.0  ODRMD  23.0     Mumbai  57.92
8    9.0  IBSQF  31.0     Mumbai  51.74
9   10.0  JOIPK  34.0    Chennai  52.61
10  11.0  NYJIZ   NaN        NaN  76.18
11  12.0  JZZUB  19.0    Chennai  64.61
12  13.0  OGLZJ  27.0  Bangalore  53.59
13  14.0  KLXTL  21.0  Bangalore  67.71
14  15.0  OZYDX  27.0  Bangalore  62.63
15  16.0  PGABU  21.0  Bangalore  78.16
16  17.0  SRSUZ  38.0    Chennai  79.51
17   NaN    NaN   NaN        NaN    NaN
18  19.0  EDEDZ  20.0  Bangalore  90.10
19  20.0  YBENN  27.0    Chennai  88.16

In [185]:
raw_data.replace(to_replace="Chennai",value="TamilNadu")

      ID   Name   Age       City  Score
0    1.0  LJQNM  32.0  Bangalore  66.15
1    2.0  OTRCJ  29.0      Delhi  73.92
2    3.0  NYAYB  30.0  Hyderabad  83.14
3    4.0  QYDTM  35.0     Mumbai  56.68
4    5.0  BXKCT  23.0  TamilNadu  69.24
5    6.0  YJOAY   NaN        NaN  83.74
6    7.0  LYZGH  18.0  TamilNadu  86.57
7    8.0  ODRMD  23.0     Mumbai  57.92
8    9.0  IBSQF  31.0     Mumbai  51.74
9   10.0  JOIPK  34.0  TamilNadu  52.61
10  11.0  NYJIZ   NaN        NaN  76.18
11  12.0  JZZUB  19.0  TamilNadu  64.61
12  13.0  OGLZJ  27.0  Bangalore  53.59
13  14.0  KLXTL  21.0  Bangalore  67.71
14  15.0  OZYDX  27.0  Bangalore  62.63
15  16.0  PGABU  21.0  Bangalore  78.16
16  17.0  SRSUZ  38.0  TamilNadu  79.51
17   NaN    NaN   NaN        NaN    NaN
18  19.0  EDEDZ  20.0  Bangalore  90.10
19  20.0  YBENN  27.0  TamilNadu  88.16

In [186]:
raw_data.replace([1,2,3,4,5,6,7,8,9],1000)

        ID   Name   Age       City  Score
0   1000.0  LJQNM  32.0  Bangalore  66.15
1   1000.0  OTRCJ  29.0      Delhi  73.92
2   1000.0  NYAYB  30.0  Hyderabad  83.14
3   1000.0  QYDTM  35.0     Mumbai  56.68
4   1000.0  BXKCT  23.0    Chennai  69.24
5   1000.0  YJOAY   NaN        NaN  83.74
6   1000.0  LYZGH  18.0    Chennai  86.57
7   1000.0  ODRMD  23.0     Mumbai  57.92
8   1000.0  IBSQF  31.0     Mumbai  51.74
9     10.0  JOIPK  34.0    Chennai  52.61
10    11.0  NYJIZ   NaN        NaN  76.18
11    12.0  JZZUB  19.0    Chennai  64.61
12    13.0  OGLZJ  27.0  Bangalore  53.59
13    14.0  KLXTL  21.0  Bangalore  67.71
14    15.0  OZYDX  27.0  Bangalore  62.63
15    16.0  PGABU  21.0  Bangalore  78.16
16    17.0  SRSUZ  38.0    Chennai  79.51
17     NaN    NaN   NaN        NaN    NaN
18    19.0  EDEDZ  20.0  Bangalore  90.10
19    20.0  YBENN  27.0    Chennai  88.16

In [187]:
raw_data.replace("[A-Za-z]","anand",regex=True)

,ID,Name,Age,City,Score
0,1.0,anandanandanandanandanand,32.0,anandanandanandanandanandanandanandanandanand,66.15
1,2.0,anandanandanandanandanand,29.0,anandanandanandanandanand,73.92
2,3.0,anandanandanandanandanand,30.0,anandanandanandanandanandanandanandanandanand,83.14
3,4.0,anandanandanandanandanand,35.0,anandanandanandanandanandanand,56.68
4,5.0,anandanandanandanandanand,23.0,anandanandanandanandanandanandanand,69.24
5,6.0,anandanandanandanandanand,NaN,NaN,83.74
6,7.0,anandanandanandanandanand,18.0,anandanandanandanandanandanandanand,86.57
7,8.0,anandanandanandanandanand,23.0,anandanandanandanandanandanand,57.92
8,9.0,anandanandanandanandanand,31.0,anandanandanandanandanandanand,51.74
9,10.0,anandanandanandanandanand,34.0,anandanandanandanandanandanandanand,52.61
10,11.0,anandanandanandanandanand,NaN,NaN,76.18
11,12.0,anandanandanandanandanand,19.0,anandanandanandanandanandanandanand,64.61
12,13.0,anandanandanandanandanand,27.0,anandanandanandanandanandanandanandanandanand,53.59
13,14.0,anandanandanandanandanand,21.0,anandanandanandanandanandanandanandanandanand,67.71
14,15.0,anandanandanandanandanand,27.0,anandanandanandanandanandanandanandanandanand,62.63
15,16.0,anandanandanandanandanand,21.0,anandanandanandanandanandanandanandanandanand,78.16
16,17.0,anandanandanandanandanand,38.0,anandanandanandanandanandanandanand,79.51
17,NaN,NaN,NaN,NaN,NaN
18,19.0,anandanandanandanandanand,20.0,anandanandanandanandanandanandanandanandanand,90.10
19,20.0,anandanandanandanandanand,27.0,anandanandanandanandanandanandanand,88.16

In [188]:
raw_data.replace({"ID":[1,2,3,4]},1000,regex=True)

        ID   Name   Age       City  Score
0   1000.0  LJQNM  32.0  Bangalore  66.15
1   1000.0  OTRCJ  29.0      Delhi  73.92
2   1000.0  NYAYB  30.0  Hyderabad  83.14
3   1000.0  QYDTM  35.0     Mumbai  56.68
4      5.0  BXKCT  23.0    Chennai  69.24
5      6.0  YJOAY   NaN        NaN  83.74
6      7.0  LYZGH  18.0    Chennai  86.57
7      8.0  ODRMD  23.0     Mumbai  57.92
8      9.0  IBSQF  31.0     Mumbai  51.74
9     10.0  JOIPK  34.0    Chennai  52.61
10    11.0  NYJIZ   NaN        NaN  76.18
11    12.0  JZZUB  19.0    Chennai  64.61
12    13.0  OGLZJ  27.0  Bangalore  53.59
13    14.0  KLXTL  21.0  Bangalore  67.71
14    15.0  OZYDX  27.0  Bangalore  62.63
15    16.0  PGABU  21.0  Bangalore  78.16
16    17.0  SRSUZ  38.0    Chennai  79.51
17     NaN    NaN   NaN        NaN    NaN
18    19.0  EDEDZ  20.0  Bangalore  90.10
19    20.0  YBENN  27.0    Chennai  88.16

In [189]:
raw_data.replace("Chennai",method="ffill")

      ID   Name   Age       City  Score
0    1.0  LJQNM  32.0  Bangalore  66.15
1    2.0  OTRCJ  29.0      Delhi  73.92
2    3.0  NYAYB  30.0  Hyderabad  83.14
3    4.0  QYDTM  35.0     Mumbai  56.68
4    5.0  BXKCT  23.0     Mumbai  69.24
5    6.0  YJOAY   NaN        NaN  83.74
6    7.0  LYZGH  18.0        NaN  86.57
7    8.0  ODRMD  23.0     Mumbai  57.92
8    9.0  IBSQF  31.0     Mumbai  51.74
9   10.0  JOIPK  34.0     Mumbai  52.61
10  11.0  NYJIZ   NaN        NaN  76.18
11  12.0  JZZUB  19.0        NaN  64.61
12  13.0  OGLZJ  27.0  Bangalore  53.59
13  14.0  KLXTL  21.0  Bangalore  67.71
14  15.0  OZYDX  27.0  Bangalore  62.63
15  16.0  PGABU  21.0  Bangalore  78.16
16  17.0  SRSUZ  38.0  Bangalore  79.51
17   NaN    NaN   NaN        NaN    NaN
18  19.0  EDEDZ  20.0  Bangalore  90.10
19  20.0  YBENN  27.0  Bangalore  88.16

In [190]:
raw_data.replace("Chennai",method="bfill")

      ID   Name   Age       City  Score
0    1.0  LJQNM  32.0  Bangalore  66.15
1    2.0  OTRCJ  29.0      Delhi  73.92
2    3.0  NYAYB  30.0  Hyderabad  83.14
3    4.0  QYDTM  35.0     Mumbai  56.68
4    5.0  BXKCT  23.0        NaN  69.24
5    6.0  YJOAY   NaN        NaN  83.74
6    7.0  LYZGH  18.0     Mumbai  86.57
7    8.0  ODRMD  23.0     Mumbai  57.92
8    9.0  IBSQF  31.0     Mumbai  51.74
9   10.0  JOIPK  34.0        NaN  52.61
10  11.0  NYJIZ   NaN        NaN  76.18
11  12.0  JZZUB  19.0  Bangalore  64.61
12  13.0  OGLZJ  27.0  Bangalore  53.59
13  14.0  KLXTL  21.0  Bangalore  67.71
14  15.0  OZYDX  27.0  Bangalore  62.63
15  16.0  PGABU  21.0  Bangalore  78.16
16  17.0  SRSUZ  38.0        NaN  79.51
17   NaN    NaN   NaN        NaN    NaN
18  19.0  EDEDZ  20.0  Bangalore  90.10
19  20.0  YBENN  27.0    Chennai  88.16

In [191]:
raw_data.replace("Chennai","Hyderabad",limit=2)

      ID   Name   Age       City  Score
0    1.0  LJQNM  32.0  Bangalore  66.15
1    2.0  OTRCJ  29.0      Delhi  73.92
2    3.0  NYAYB  30.0  Hyderabad  83.14
3    4.0  QYDTM  35.0     Mumbai  56.68
4    5.0  BXKCT  23.0  Hyderabad  69.24
5    6.0  YJOAY   NaN        NaN  83.74
6    7.0  LYZGH  18.0  Hyderabad  86.57
7    8.0  ODRMD  23.0     Mumbai  57.92
8    9.0  IBSQF  31.0     Mumbai  51.74
9   10.0  JOIPK  34.0  Hyderabad  52.61
10  11.0  NYJIZ   NaN        NaN  76.18
11  12.0  JZZUB  19.0  Hyderabad  64.61
12  13.0  OGLZJ  27.0  Bangalore  53.59
13  14.0  KLXTL  21.0  Bangalore  67.71
14  15.0  OZYDX  27.0  Bangalore  62.63
15  16.0  PGABU  21.0  Bangalore  78.16
16  17.0  SRSUZ  38.0  Hyderabad  79.51
17   NaN    NaN   NaN        NaN    NaN
18  19.0  EDEDZ  20.0  Bangalore  90.10
19  20.0  YBENN  27.0  Hyderabad  88.16

In [192]:
# raw_data.replace("Chennai","Hyderabad",limit=2,inplace=True)
# raw_data

# interpolate

In [193]:
raw_data.interpolate()

      ID   Name   Age       City   Score
0    1.0  LJQNM  32.0  Bangalore  66.150
1    2.0  OTRCJ  29.0      Delhi  73.920
2    3.0  NYAYB  30.0  Hyderabad  83.140
3    4.0  QYDTM  35.0     Mumbai  56.680
4    5.0  BXKCT  23.0    Chennai  69.240
5    6.0  YJOAY  20.5        NaN  83.740
6    7.0  LYZGH  18.0    Chennai  86.570
7    8.0  ODRMD  23.0     Mumbai  57.920
8    9.0  IBSQF  31.0     Mumbai  51.740
9   10.0  JOIPK  34.0    Chennai  52.610
10  11.0  NYJIZ  26.5        NaN  76.180
11  12.0  JZZUB  19.0    Chennai  64.610
12  13.0  OGLZJ  27.0  Bangalore  53.590
13  14.0  KLXTL  21.0  Bangalore  67.710
14  15.0  OZYDX  27.0  Bangalore  62.630
15  16.0  PGABU  21.0  Bangalore  78.160
16  17.0  SRSUZ  38.0    Chennai  79.510
17  18.0    NaN  29.0        NaN  84.805
18  19.0  EDEDZ  20.0  Bangalore  90.100
19  20.0  YBENN  27.0    Chennai  88.160

In [194]:
raw_data.interpolate(method="linear",axis=0)

      ID   Name   Age       City   Score
0    1.0  LJQNM  32.0  Bangalore  66.150
1    2.0  OTRCJ  29.0      Delhi  73.920
2    3.0  NYAYB  30.0  Hyderabad  83.140
3    4.0  QYDTM  35.0     Mumbai  56.680
4    5.0  BXKCT  23.0    Chennai  69.240
5    6.0  YJOAY  20.5        NaN  83.740
6    7.0  LYZGH  18.0    Chennai  86.570
7    8.0  ODRMD  23.0     Mumbai  57.920
8    9.0  IBSQF  31.0     Mumbai  51.740
9   10.0  JOIPK  34.0    Chennai  52.610
10  11.0  NYJIZ  26.5        NaN  76.180
11  12.0  JZZUB  19.0    Chennai  64.610
12  13.0  OGLZJ  27.0  Bangalore  53.590
13  14.0  KLXTL  21.0  Bangalore  67.710
14  15.0  OZYDX  27.0  Bangalore  62.630
15  16.0  PGABU  21.0  Bangalore  78.160
16  17.0  SRSUZ  38.0    Chennai  79.510
17  18.0    NaN  29.0        NaN  84.805
18  19.0  EDEDZ  20.0  Bangalore  90.100
19  20.0  YBENN  27.0    Chennai  88.160

In [200]:
raw_data.interpolate(limit=1,limit_direction="forward")

      ID   Name   Age       City   Score
0    1.0  LJQNM  32.0  Bangalore  66.150
1    2.0  OTRCJ  29.0      Delhi  73.920
2    3.0  NYAYB  30.0  Hyderabad  83.140
3    4.0  QYDTM  35.0     Mumbai  56.680
4    5.0  BXKCT  23.0    Chennai  69.240
5    6.0  YJOAY  20.5        NaN  83.740
6    7.0  LYZGH  18.0    Chennai  86.570
7    8.0  ODRMD  23.0     Mumbai  57.920
8    9.0  IBSQF  31.0     Mumbai  51.740
9   10.0  JOIPK  34.0    Chennai  52.610
10  11.0  NYJIZ  26.5        NaN  76.180
11  12.0  JZZUB  19.0    Chennai  64.610
12  13.0  OGLZJ  27.0  Bangalore  53.590
13  14.0  KLXTL  21.0  Bangalore  67.710
14  15.0  OZYDX  27.0  Bangalore  62.630
15  16.0  PGABU  21.0  Bangalore  78.160
16  17.0  SRSUZ  38.0    Chennai  79.510
17  18.0    NaN  29.0        NaN  84.805
18  19.0  EDEDZ  20.0  Bangalore  90.100
19  20.0  YBENN  27.0    Chennai  88.160

In [196]:
raw_data.interpolate(limit=1,limit_direction="backward")

      ID   Name   Age       City   Score
0    1.0  LJQNM  32.0  Bangalore  66.150
1    2.0  OTRCJ  29.0      Delhi  73.920
2    3.0  NYAYB  30.0  Hyderabad  83.140
3    4.0  QYDTM  35.0     Mumbai  56.680
4    5.0  BXKCT  23.0    Chennai  69.240
5    6.0  YJOAY  20.5        NaN  83.740
6    7.0  LYZGH  18.0    Chennai  86.570
7    8.0  ODRMD  23.0     Mumbai  57.920
8    9.0  IBSQF  31.0     Mumbai  51.740
9   10.0  JOIPK  34.0    Chennai  52.610
10  11.0  NYJIZ  26.5        NaN  76.180
11  12.0  JZZUB  19.0    Chennai  64.610
12  13.0  OGLZJ  27.0  Bangalore  53.590
13  14.0  KLXTL  21.0  Bangalore  67.710
14  15.0  OZYDX  27.0  Bangalore  62.630
15  16.0  PGABU  21.0  Bangalore  78.160
16  17.0  SRSUZ  38.0    Chennai  79.510
17  18.0    NaN  29.0        NaN  84.805
18  19.0  EDEDZ  20.0  Bangalore  90.100
19  20.0  YBENN  27.0    Chennai  88.160

In [201]:
raw_data.interpolate(limit=1,limit_direction="both")

      ID   Name   Age       City   Score
0    1.0  LJQNM  32.0  Bangalore  66.150
1    2.0  OTRCJ  29.0      Delhi  73.920
2    3.0  NYAYB  30.0  Hyderabad  83.140
3    4.0  QYDTM  35.0     Mumbai  56.680
4    5.0  BXKCT  23.0    Chennai  69.240
5    6.0  YJOAY  20.5        NaN  83.740
6    7.0  LYZGH  18.0    Chennai  86.570
7    8.0  ODRMD  23.0     Mumbai  57.920
8    9.0  IBSQF  31.0     Mumbai  51.740
9   10.0  JOIPK  34.0    Chennai  52.610
10  11.0  NYJIZ  26.5        NaN  76.180
11  12.0  JZZUB  19.0    Chennai  64.610
12  13.0  OGLZJ  27.0  Bangalore  53.590
13  14.0  KLXTL  21.0  Bangalore  67.710
14  15.0  OZYDX  27.0  Bangalore  62.630
15  16.0  PGABU  21.0  Bangalore  78.160
16  17.0  SRSUZ  38.0    Chennai  79.510
17  18.0    NaN  29.0        NaN  84.805
18  19.0  EDEDZ  20.0  Bangalore  90.100
19  20.0  YBENN  27.0    Chennai  88.160

In [202]:
raw_data.interpolate(limit_area='inside')

      ID   Name   Age       City   Score
0    1.0  LJQNM  32.0  Bangalore  66.150
1    2.0  OTRCJ  29.0      Delhi  73.920
2    3.0  NYAYB  30.0  Hyderabad  83.140
3    4.0  QYDTM  35.0     Mumbai  56.680
4    5.0  BXKCT  23.0    Chennai  69.240
5    6.0  YJOAY  20.5        NaN  83.740
6    7.0  LYZGH  18.0    Chennai  86.570
7    8.0  ODRMD  23.0     Mumbai  57.920
8    9.0  IBSQF  31.0     Mumbai  51.740
9   10.0  JOIPK  34.0    Chennai  52.610
10  11.0  NYJIZ  26.5        NaN  76.180
11  12.0  JZZUB  19.0    Chennai  64.610
12  13.0  OGLZJ  27.0  Bangalore  53.590
13  14.0  KLXTL  21.0  Bangalore  67.710
14  15.0  OZYDX  27.0  Bangalore  62.630
15  16.0  PGABU  21.0  Bangalore  78.160
16  17.0  SRSUZ  38.0    Chennai  79.510
17  18.0    NaN  29.0        NaN  84.805
18  19.0  EDEDZ  20.0  Bangalore  90.100
19  20.0  YBENN  27.0    Chennai  88.160

In [203]:
raw_data.interpolate(limit_area='outside')

      ID   Name   Age       City  Score
0    1.0  LJQNM  32.0  Bangalore  66.15
1    2.0  OTRCJ  29.0      Delhi  73.92
2    3.0  NYAYB  30.0  Hyderabad  83.14
3    4.0  QYDTM  35.0     Mumbai  56.68
4    5.0  BXKCT  23.0    Chennai  69.24
5    6.0  YJOAY   NaN        NaN  83.74
6    7.0  LYZGH  18.0    Chennai  86.57
7    8.0  ODRMD  23.0     Mumbai  57.92
8    9.0  IBSQF  31.0     Mumbai  51.74
9   10.0  JOIPK  34.0    Chennai  52.61
10  11.0  NYJIZ   NaN        NaN  76.18
11  12.0  JZZUB  19.0    Chennai  64.61
12  13.0  OGLZJ  27.0  Bangalore  53.59
13  14.0  KLXTL  21.0  Bangalore  67.71
14  15.0  OZYDX  27.0  Bangalore  62.63
15  16.0  PGABU  21.0  Bangalore  78.16
16  17.0  SRSUZ  38.0    Chennai  79.51
17   NaN    NaN   NaN        NaN    NaN
18  19.0  EDEDZ  20.0  Bangalore  90.10
19  20.0  YBENN  27.0    Chennai  88.16

In [206]:
# raw_data.interpolate(inplace=False)

In [205]:
raw_data

      ID   Name   Age       City  Score
0    1.0  LJQNM  32.0  Bangalore  66.15
1    2.0  OTRCJ  29.0      Delhi  73.92
2    3.0  NYAYB  30.0  Hyderabad  83.14
3    4.0  QYDTM  35.0     Mumbai  56.68
4    5.0  BXKCT  23.0    Chennai  69.24
5    6.0  YJOAY   NaN        NaN  83.74
6    7.0  LYZGH  18.0    Chennai  86.57
7    8.0  ODRMD  23.0     Mumbai  57.92
8    9.0  IBSQF  31.0     Mumbai  51.74
9   10.0  JOIPK  34.0    Chennai  52.61
10  11.0  NYJIZ   NaN        NaN  76.18
11  12.0  JZZUB  19.0    Chennai  64.61
12  13.0  OGLZJ  27.0  Bangalore  53.59
13  14.0  KLXTL  21.0  Bangalore  67.71
14  15.0  OZYDX  27.0  Bangalore  62.63
15  16.0  PGABU  21.0  Bangalore  78.16
16  17.0  SRSUZ  38.0    Chennai  79.51
17   NaN    NaN   NaN        NaN    NaN
18  19.0  EDEDZ  20.0  Bangalore  90.10
19  20.0  YBENN  27.0    Chennai  88.16

# merge

In [214]:
a = pd.DataFrame({"A":[1,2,3,4],"B":[5,6,7,8]})
b = pd.DataFrame({"A":[1,2,3,10],"c":[5,6,7,10]})
pd.merge(a,b)

   A  B  c
0  1  5  5
1  2  6  6
2  3  7  7

In [216]:
pd.merge(a,b,how="left")

   A  B    c
0  1  5  5.0
1  2  6  6.0
2  3  7  7.0
3  4  8  NaN

In [217]:
pd.merge(a,b,how="right")

    A    B   c
0   1  5.0   5
1   2  6.0   6
2   3  7.0   7
3  10  NaN  10

In [219]:
pd.merge(a,b,how="outer")

    A    B     c
0   1  5.0   5.0
1   2  6.0   6.0
2   3  7.0   7.0
3   4  8.0   NaN
4  10  NaN  10.0

In [220]:
pd.merge(a,b,how="inner")

   A  B  c
0  1  5  5
1  2  6  6
2  3  7  7

In [225]:
c=pd.DataFrame({"A":[1,2,3,4],"B":[2,3,4,5]})
d=pd.DataFrame({"A":[3,4,5,6],"B":[4,5,6,7]})

pd.merge(c,d,right_index=True,left_index=True,suffixes=("anand","vaish"))

   Aanand  Banand  Avaish  Bvaish
0       1       2       3       4
1       2       3       4       5
2       3       4       5       6
3       4       5       6       7

# concat